name: megan_sin
description: A Flutter website.

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  animated_text_kit: ^4.2.2
  awesome: ^0.0.3
  google_fonts: ^6.1.0
  url_launcher: ^6.0.0
  font_awesome_flutter: ^10.6.0
  flutter_image_slideshow: ^0.1.6
  pdfx:
    git:
      url: 'https://github.com/ScerIO/packages.flutter'
      ref: '4be9de9ffed5398fd7d5f44bbb07dcd3d3f1711b'
      path: packages/pdfx

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
      - assets/megan_sin_headshot.png
      - assets/megan_sin_resume.pdf
      - assets/frog_sonny_angel.png
      - assets/poetry_pal/rating 1.png
      - assets/poetry_pal/rating 2.png
      - assets/poetry_pal/rating 3.png
      - assets/ai_resume_parser/home.png
      - assets/data4good/approach.png
      - assets/data4good/exec_summary.png
      - assets/data4good/recommendations.png
      - assets/f1/example.png
      - assets/f1/example2.png
      - assets/iqp/figure3.png
      - assets/iqp/barchart.png
      - assets/iqp/short_term_suggestion.png
      - assets/spotbot/process_flowchart.png
      - assets/spotbot/results.png
      - assets/stroke/corr_matrix.png
      - assets/stroke/approach1.png
      - assets/stroke/approach2.png
      - assets/stroke/results.png

  uses-material-design: true
